### PR TITLE
Some fixes for Windows

### PR DESCRIPTION
**Pull request by mchelifpv**

### CODE REVIEW

**Comment by t-asano** [comment]
Thank you. I will review it.

**Comment by t-asano** [comment]
> Fix Windows locale detection https://github.com/t-asano/tinyviewplus/pull/24/commits/8efb8afb90deeaf40cf1b900ca3c6a3446fd13be

OK.

**Comment by t-asano** [comment]
> Remove Windows console at startup https://github.com/t-asano/tinyviewplus/pull/24/commits/f453cf850f51980f2e7d40df2366de7e52651150

OK. I will update HowToBuild.md (Sorry, written in Japanese).

**Comment by t-asano** [comment]
> Change startup screen keypress logic https://github.com/t-asano/tinyviewplus/pull/24/commits/07ebf5912bbe45e672b23776d49ff328235fce91

OK. I may change the message later.

**Comment by t-asano** [comment]
> Remove version info and system clock via main screen https://github.com/t-asano/tinyviewplus/pull/24/commits/cbea8153467b41e5c1dfc6aa9cac51ad69f86cf1

OK.

**Comment by t-asano** [comment]
> Improve remaining time https://github.com/t-asano/tinyviewplus/pull/24/commits/71247437460f4b90ea560fed8a94bd099af116d7

typo:
```
- // ...80,120,60,30,5..1,0
+ // ...180,120,60,30,5..1,0
```

It might be better (I am not sure because I am not a native speaker).
```
- str += " second";
+ str += " seconds";
```

I will make small change at Japanese speech later.

**Comment by t-asano** [comment]
> Minimum Lap time set via Page_Up/Page_Down keys https://github.com/t-asano/tinyviewplus/pull/24/commits/908c8ecb3299f3a1f66a9e0b2384ab6aac9fd9fa

The logic is fine.

I prefer help text:
- Windows -> "PgUp/PgDown"
- macOS -> "fn + Up/Down"

I will update README later.

**Comment by t-asano** [comment]
> Setup race laps and time via cursor keys https://github.com/t-asano/tinyviewplus/pull/24/commits/0ba2eede648fa7b62c67627034a42855eaa98fa1

I would like to keep the existing feature (direct input after D key).
Some people need it to set very large value.

For a new feature, I suggest variable speed.
- Time:
  - <= 1 hour: 10 seconds / step
  - \> 1 hour: 1 hour / step
- Lap:
  - <= 100 laps: 1 lap / step
  - \> 100 laps: 100 laps / step

I may change the message later.

**Comment by t-asano** [comment]
> Fix Window title https://github.com/t-asano/tinyviewplus/pull/24/commits/3fb50b6470618229f836d6a5222e87ce6c57aeca

OK.

**Comment by t-asano** [comment]
> Remove small logo https://github.com/t-asano/tinyviewplus/pull/24/commits/22c3634b5b06071804e38f889f91d1336ae2309d

I suggest:
- keep logo.
- remove "Tiny View Plus" from lower left text "Tiny View Plus v0.9.xx".

**Comment by t-asano** [comment]
> Save and load pilot labels https://github.com/t-asano/tinyviewplus/pull/24/commits/ccf3281d478dd5b2c662668ab7a22582d4722cfa

OK.

It may be better for the pilot number in the XML file to start from 1.

**Comment by t-asano** [comment]
@mchelifpv 
Thanks for the useful suggestions.
Which do you prefer as a next action?
- Plan A: You refine and I will review later.
- Plan B: I merge as is and refine later. (several weeks needed)

**Comment by mchelifpv** [comment]
> @mchelifpv
> Thanks for the useful suggestions.
> Which do you prefer as a next action?
> 
>     * Plan A: You refine and I will review later.
> 
>     * Plan B: I merge as is and refine later. (several weeks needed)

To be honest, I don’t know how best deal with all this. Now I am engaged in internationalizing the program through xml language files. Some of my friends do not speak English and do not understand what  "iron lady" is talking. In progress I found some errors of code and fix it, but do not commit. There were too many changes before.

**Comment by t-asano** [comment]
>  (several weeks needed)
all done!

**Pull request merged**
